/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-101749-g55d1caa49c-g797c2ecc8f+1"
#endif /* AVUTIL_FFVERSION_H */
